import { BeeSpecies } from '@/types/ConstantsTypes';
export const species: BeeSpecies[] = [
  {
    id: 1,
    name: 'Mombucão, Mombuca',
    scientificName: 'Cephalotrigona capitata',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Cephalo_capitata.jpg',
  },
  {
    id: 2,
    name: 'Mombucão-da-Amazônia',
    scientificName: 'Cephalotrigona femorata',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/09/Cephalotrigona_femorata.jpg',
  },
  {
    id: 3,
    name: 'Caça-Abelha-Limão, Caçadora-De-Limão',
    scientificName: 'Duckeola ghilianii',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Duckeola_ghilianii.jpg',
  },
  {
    id: 4,
    name: 'Mirim-Preguiça',
    scientificName: 'Friesella schrottkyi',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Friesella_schrottkyi.jpg',
  },
  {
    id: 5,
    name: 'Moça-Branca, Abelha-Branca',
    scientificName: 'Frieseomelitta doederleini',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Frieseomelitta_doederleini.jpg',
  },
  {
    id: 6,
    name: 'Moça-Branca, Marmelada-Amarela-Mais-Mansa',
    scientificName: 'Frieseomelitta flavicornis',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Frieseomelitta_flavicornis.jpg',
  },
  {
    id: 7,
    name: 'Mocinha-Preta, Marmelada-Preta',
    scientificName: 'Frieseomelitta languida',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Frieseomelitta_languida.jpg',
  },
  {
    id: 8,
    name: 'Marmelada',
    scientificName: 'Frieseomelitta longipes',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Frieseomelitaa_longipes.jpg',
  },
  {
    id: 9,
    name: 'Moça-Branca',
    scientificName: 'Frieseomelitta meadewaldoi',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/09/imagem-nao-disponivel.png',
  },
  {
    id: 10,
    name: 'Mocinha-Preta, Moça-Preta, Marmelada-Preta',
    scientificName: 'Frieseomelitta silvestrii',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/09/Frieseomelitta_silvestrii.jpg',
  },
  {
    id: 11,
    name: 'Marmelada, Marmelada-Amarela, Manoel-De-Abreu, Zamboque',
    scientificName: 'Frieseomelitta varia',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Frieseomelitta_varia.jpg',
  },
  {
    id: 12,
    name: 'Geotrigona Fulvohirta',
    scientificName: 'Geotrigona fulvohirta',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/09/Geotrigona_fulvohirta.jpg',
  },
  {
    id: 13,
    name: 'Guira, Mombuca',
    scientificName: 'Geotrigona mombuca',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Geotrigona_mombuca.jpg',
  },
  {
    id: 14,
    name: 'Lambe-Olhos, Mirim',
    scientificName: 'Leurotrigona muelleri',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Leurotrigona_muelleri.jpg',
  },
  {
    id: 15,
    name: 'Melipona Amazônica',
    scientificName: 'Melipona amazonica',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/09/Melipona_amazonica.jpg',
  },
  {
    id: 16,
    name: 'Rajada, Munduri',
    scientificName: 'Melipona asilvai',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_asilvai.jpg',
  },
  {
    id: 17,
    name: 'Guaraipo, Guarupu',
    scientificName: 'Melipona bicolor',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_bicolor1.jpg',
  },
  {
    id: 18,
    name: 'Uruçu-Preta, Uruçu-Capixaba',
    scientificName: 'Melipona capixaba',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_capixaba.jpg',
  },
  {
    id: 19,
    name: 'Uruçu-Amarela',
    scientificName: 'Melipona captiosa',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/09/Melipona_captiosa.jpg',
  },
  {
    id: 20,
    name: 'Jupará',
    scientificName: 'Melipona compressipes',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/09/Melipona_compressipes.jpg',
  },
  {
    id: 21,
    name: 'Melipona Cramptoni',
    scientificName: 'Melipona cramptoni',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Melipona_cramptoni.jpg',
  },
  {
    id: 22,
    name: 'Uruçu-Amarela-Avermelhada, Jandaíra-Maior',
    scientificName: 'Melipona crinita',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_crinita.jpg',
  },
  {
    id: 23,
    name: 'Melipona Dubia',
    scientificName: 'Melipona dubia',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Melipona_dubia.jpg',
  },
  {
    id: 24,
    name: 'Uruçu-Beiço',
    scientificName: 'Melipona eburnea',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_eburnea.jpg',
  },
  {
    id: 25,
    name: 'Tiúba, Uruçu-Cinzenta, Jandaíra-Preta-Da-Amazônia',
    scientificName: 'Melipona fasciculata',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_fasciculata.jpg',
  },
  {
    id: 26,
    name: 'Uruçu-Amarela, Ira-Açu',
    scientificName: 'Melipona flavolineata',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_flavolineata.jpg',
  },
  {
    id: 27,
    name: 'Turuçu, Uruçu-Boi',
    scientificName: 'Melipona fuliginosa',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_fuliginosa.jpg',
  },
  {
    id: 28,
    name: 'Jandaíra-Fulva, Uruçu-Amarela',
    scientificName: 'Melipona fulva',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_fulva.jpg',
  },
  {
    id: 29,
    name: 'Uruçu-Beiço',
    scientificName: 'Melipona fuscopilosa',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Melipona_fuscopilosa.jpg',
  },
  {
    id: 30,
    name: 'Jupará-Grande',
    scientificName: 'Melipona grandis',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Melipona_grandis.jpg',
  },
  {
    id: 31,
    name: 'Melipona Illustris',
    scientificName: 'Melipona illustris',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Melipona_illustris.jpg',
  },
  {
    id: 32,
    name: 'Jandaíra-Preta-Da-Amazônia, Jupará',
    scientificName: 'Melipona interrupta',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_interrupta.jpg',
  },
  {
    id: 33,
    name: 'Uruçu-Canudo, Pinto-De-Velho',
    scientificName: 'Melipona lateralis',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_lateralis.jpg',
  },
  {
    id: 34,
    name: 'Mandaçaia, Mandaçaia-Menor',
    scientificName: 'Melipona mandacaia',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_mandacaia.jpg',
  },
  {
    id: 35,
    name: 'Manduri',
    scientificName: 'Melipona marginata',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/09/Melipona_marginata_Lateral.jpg',
  },
  {
    id: 36,
    name: 'Uruçu-Da-Barriga-Preta, Uruçu-Sem-Canudo',
    scientificName: 'Melipona melanoventer',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_melanoventer.jpg',
  },
  {
    id: 37,
    name: 'Bugia, Monduri',
    scientificName: 'Melipona mondury',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_mondury.jpg',
  },
  {
    id: 38,
    name: 'Uruçu-De-Olho-Verde',
    scientificName: 'Melipona nebulosa',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Melipona_nebulosa.jpg',
  },
  {
    id: 39,
    name: 'Melipona Ogilviei',
    scientificName: 'Melipona ogilviei',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Melipona_ogilviei.jpg',
  },
  {
    id: 40,
    name: 'Manduri-De-Mato-Grosso, Manduri',
    scientificName: 'Melipona orbignyi',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_orbignyi.jpg',
  },
  {
    id: 41,
    name: 'Uruçu-Boca-De-Ralo, Uruçu-Do-Pará',
    scientificName: 'Melipona paraensis',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_paraensis.jpg',
  },
  {
    id: 42,
    name: 'Uruçu-Amarela-Preguiçosa',
    scientificName: 'Melipona puncticollis',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Melipona_puncticollis.jpg',
  },
  {
    id: 43,
    name: 'Mandaçaia',
    scientificName: 'Melipona quadrifasciata',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_quadrifasciata.jpg',
  },
  {
    id: 44,
    name: 'Uruçu-Do-Chão, Mandaçaia-Do-Chão',
    scientificName: 'Melipona quinquefasciata',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_quinquefasciata.jpg',
  },
  {
    id: 45,
    name: 'Uruçu-Amarela, Tujuba',
    scientificName: 'Melipona rufiventris',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_rufiventris.jpg',
  },
  {
    id: 46,
    name: 'Uruçu, Uruçu-Nordestina',
    scientificName: 'Melipona scutellaris',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_scutellaris.jpg',
  },
  {
    id: 47,
    name: 'Uruçu-Boca-De-Renda, Jandaíra-Alaranjada-De-Manaus',
    scientificName: 'Melipona seminigra',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_seminigra_pernigra.jpg',
  },
  {
    id: 48,
    name: 'Jandaíra',
    scientificName: 'Melipona subnitida',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_subnitida.jpg',
  },
  {
    id: 49,
    name: 'Mondori, Manduri',
    scientificName: 'Melipona torrida',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Melipona_torrida.jpg',
  },
  {
    id: 50,
    name: 'Ichoa-Choca-Menor',
    scientificName: 'Melipona tumupasae',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Melipona_tumupasae.jpg',
  },
  {
    id: 51,
    name: 'Iraí',
    scientificName: 'Nannotrigona chapadana',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Nannotrigona_chapadana.jpg',
  },
  {
    id: 52,
    name: 'Mosquito-Do-Chão, Jataí-Da-Terra',
    scientificName: 'Paratrigona lineata',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Paratrigona_lineata.jpg',
  },
  {
    id: 53,
    name: 'Paratrigona Peltata',
    scientificName: 'Paratrigona peltata',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Paratrigona_peltata.jpg',
  },
  {
    id: 54,
    name: 'Jataí-Da-Terra, Mirim-Sem-Brilho',
    scientificName: 'Paratrigona subnuda',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Paratrigona_subnuda_.jpg',
  },
  {
    id: 55,
    name: 'Boca-De-Sapo, Cupira',
    scientificName: 'Partamona cupira',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Partamona_cupira.jpg',
  },
  {
    id: 56,
    name: 'Cupira',
    scientificName: 'Partamona seridoensis',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Partamona_seridoensis.jpg',
  },
  {
    id: 57,
    name: 'Mosquito',
    scientificName: 'Plebeia alvarengai',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Plebeia_alvarengai.jpg',
  },
  {
    id: 58,
    name: 'Mirim-Droriana',
    scientificName: 'Plebeia droryana',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Plebeia_droryana.jpg',
  },
  {
    id: 59,
    name: 'Mirim-Emerina',
    scientificName: 'Plebeia emerina',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Plebeia_emerina.jpg',
  },
  {
    id: 60,
    name: 'Jati, Abelha-Mosquito',
    scientificName: 'Plebeia flavocincta',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Plebeia_flavocincta.jpg',
  },
  {
    id: 61,
    name: 'Mirim-Preguiça-Preta',
    scientificName: 'Plebeia julianii',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Plebeia_julianii.jpg',
  },
  {
    id: 62,
    name: 'Mirim-Luci',
    scientificName: 'Plebeia lucii',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Plebeia_lucii.jpg',
  },
  {
    id: 63,
    name: 'Abelha-Mosquito, Lambe-Lágrima',
    scientificName: 'Plebeia minima',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Plebeia_minima.jpg',
  },
  {
    id: 64,
    name: 'Mosquito',
    scientificName: 'Plebeia mosquito',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/09/imagem-nao-disponivel.png',
  },
  {
    id: 65,
    name: 'Mirim-Nigriceps, Mirí',
    scientificName: 'Plebeia nigriceps',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Plebeia_nigriceps.jpg',
  },
  {
    id: 66,
    name: 'Mirim-Guaçú, Mirim-Guaçú-Amarela',
    scientificName: 'Plebeia poecilochroa',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Plebeia_poecilochroa.jpg',
  },
  {
    id: 67,
    name: 'Mirim-Remota, Mirim-Guaçu',
    scientificName: 'Plebeia remota',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Plebeia_remota_Habitus.jpg',
  },
  {
    id: 68,
    name: 'Mirim-Saiqui, Mirim',
    scientificName: 'Plebeia saiqui',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Plebeia_saiqui.jpg',
  },
  {
    id: 69,
    name: 'Tubuna, Canudo',
    scientificName: 'Scaptotrigona bipunctata',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Scaptotrigona_bipunctata.jpg',
  },
  {
    id: 70,
    name: 'Mandaguari, Tubiba, Canudo',
    scientificName: 'Scaptotrigona depilis',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Scaptotrigona_depilis.jpg',
  },
  {
    id: 71,
    name: 'Benjoí, Bijuí',
    scientificName: 'Scaptotrigona polysticta',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Scaptotrigona_polysticta.jpg',
  },
  {
    id: 72,
    name: 'Mandaguari, Canudo',
    scientificName: 'Scaptotrigona postica',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Scaptotrigona_postica.jpg',
  },
  {
    id: 73,
    name: 'Mandaguari-Preta',
    scientificName: 'Scaptotrigona tricolorata',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Scaptotrigona_tricolorata.jpg',
  },
  {
    id: 74,
    name: 'Tubiba, Tubi',
    scientificName: 'Scaptotrigona tubiba',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Scaptotrigona_tubiba.jpg',
  },
  {
    id: 75,
    name: 'Mandaguari-Amarela, Canudo-Amarela',
    scientificName: 'Scaptotrigona xanthotricha',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Scaptotrigona_xanthotricha.jpg',
  },
  {
    id: 76,
    name: 'Jataí-Preta',
    scientificName: 'Scaura longula',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Scaura_longula.jpg',
  },
  {
    id: 77,
    name: 'Guiruçu, Irussu-Do-Chão',
    scientificName: 'Schwarziana quadripunctata',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Schwarziana_quadripunctata.jpg',
  },
  {
    id: 78,
    name: 'Borá, Jataizão',
    scientificName: 'Tetragona clavipes',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Tetragona_clavipes.jpg',
  },
  {
    id: 79,
    name: 'Tetragona Essequiboensis',
    scientificName: 'Tetragona essequiboensis',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Tetragona_essequiboensis.jpg',
  },
  {
    id: 80,
    name: 'Borá-Mansa',
    scientificName: 'Tetragona goettei',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Tetragona_goettei.jpg',
  },
  {
    id: 81,
    name: 'Borá',
    scientificName: 'Tetragona kaieteurensis',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/09/imagem-nao-disponivel.png',
  },
  {
    id: 82,
    name: 'Borá, Bora-De-Chão',
    scientificName: 'Tetragona quadrangula',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Tetragona_quadrangula_.jpg',
  },
  {
    id: 83,
    name: 'Jataí, Jaty',
    scientificName: 'Tetragonisca angustula',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Tetragonisca_angustula.jpg',
  },
  {
    id: 84,
    name: 'Abelhas-Ouro, Jataí-Do-Sul',
    scientificName: 'Tetragonisca fiebrigi',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Tetragonisca_fiebrigi.jpg',
  },
  {
    id: 85,
    name: 'Jataí-Acreana',
    scientificName: 'Tetragonisca weyrauchi',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Tetragonisca_weyrauchi.jpg',
  },
  {
    id: 86,
    name: 'Trigona Cilipes',
    scientificName: 'Trigona cilipes',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Trigona_cilipes.jpg',
  },
  {
    id: 87,
    name: 'Olho-De-Vidro, Irapuá-Amarela',
    scientificName: 'Trigona pallens',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/06/Trigona_pallens.jpg',
  },
  {
    id: 88,
    name: 'Trigonisca Duckei',
    scientificName: 'Trigonisca duckei',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Trigonisca_duckei.jpg',
  },
  {
    id: 89,
    name: 'Trigonisca Pediculana',
    scientificName: 'Trigonisca pediculana',
    imageUrl: 'https://abelha.org.br/wp-content/uploads/2023/08/Trigonisca_pediculana.jpg',
  },
];
