export const states = [
    { id: 1, name: 'Acre (AC)' },
    { id: 2, name: 'Alagoas (AL)' },
    { id: 3, name: 'Amapá (AP)' },
    { id: 4, name: 'Amazonas (AM)' },
    { id: 5, name: 'Bahia (BA)' },
    { id: 6, name: 'Ceará (CE)' },
    { id: 7, name: 'Distrito Federal (DF)' },
    { id: 8, name: 'Espírito Santo (ES)' },
    { id: 9, name: 'Goiás (GO)' },
    { id: 10, name: 'Maranhão (MA)' },
    { id: 11, name: 'Mato Grosso (MT)' },
    { id: 12, name: 'Mato Grosso do Sul (MS)' },
    { id: 13, name: 'Minas Gerais (MG)' },
    { id: 14, name: 'Pará (PA)' },
    { id: 15, name: 'Paraíba (PB)' },
    { id: 16, name: 'Paraná (PR)' },
    { id: 17, name: 'Pernambuco (PE)' },
    { id: 18, name: 'Piauí (PI)' },
    { id: 19, name: 'Rio de Janeiro (RJ)' },
    { id: 20, name: 'Rio Grande do Norte (RN)' },
    { id: 21, name: 'Rio Grande do Sul (RS)' },
    { id: 22, name: 'Rondônia (RO)' },
    { id: 23, name: 'Roraima (RR)' },
    { id: 24, name: 'Santa Catarina (SC)' },
    { id: 25, name: 'São Paulo (SP)' },
    { id: 26, name: 'Sergipe (SE)' },
    { id: 27, name: 'Tocantins (TO)' },
];
